config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'currency_pairs#index'

  resources :currency_pairs, only: :index

  post 'find_pair', to: 'currency_pairs#find_pair'

  namespace :admin do
    match '/', to: 'currency_pairs#edit',   via: :get
    match '/', to: 'currency_pairs#update', via: :patch
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/currency.rb
class Currency < ApplicationRecord
  has_many :currency_pairs, foreign_key: 'base_id', class_name: 'CurrencyPair'
  has_many :currency_pairs, foreign_key: 'quote_id', class_name: 'CurrencyPair'

  validates :name, :sign, :code, presence: true
  validates :code, uniqueness: true

  validates :code, length: { is: 3 }

end

app/models/currency_pair.rb
class CurrencyPair < ApplicationRecord
  belongs_to :base,  class_name: 'Currency', foreign_key: 'base_id'
  belongs_to :quote, class_name: 'Currency', foreign_key: 'quote_id'

  validates :price, presence: true

  after_create :make_pair

  def clear_date_force
    update!(date_force: nil)
  end

  private

  def make_pair
    base = self.base.code + self.quote.code
    update!(pair: base)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_required!

  private

  def admin_required!
    redirect_to root_path, alert: 'Доступ закрыт', status: :forbidden unless current_user.admin?
  end
end

app/controllers/admin/currency_pairs_controller.rb
class Admin::CurrencyPairsController < Admin::BaseController
  after_action :scheduler_in, only: :update
  after_action :publish_course, only: :update

  def edit; end

  def update
    if pair.update(pair_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  helper_method :pair, :currencies

  def currencies
    @currencies ||= Currency.all
  end

  def pair
    @pair ||= CurrencyPair.find_by(pair: 'USDRUB')
  end

  def pair_params
    params.require(:currency_pair).permit(:price, :date_force)
  end

  def scheduler_in
    return if pair.errors.any?

    Services::Scheduler.new.update_currency_rate(pair)
  end

  def publish_course
    hash_pairs = CurrencyPair.pluck(:id, :price).to_h

    ActionCable.server.broadcast(
        'publish_course',
        { pairs: hash_pairs }
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/currency_pairs_controller.rb
class CurrencyPairsController < ApplicationController
  def index
    @pair = CurrencyPair.find_by(pair: 'USDRUB')
    @currencies = Currency.all
  end

  def find_pair
    if pair_itself?
      currency = Currency.find_by(code: params['currency_base'])
      @currency_pairs = CurrencyPair.new(pair: make_pair, quote: currency, base: currency, price: 1.0)
    else
      @currency_pairs = CurrencyPair.find_by(pair: make_pair)
    end

    render json: @currency_pairs, each_serializer: CurrencyPairSerializer
  end

  private

  def make_pair
    params['currency_base'] + params['currency_quote']
  end

  def pair_itself?
    params['currency_base'] == params['currency_quote']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/currency_pairs_helper.rb
module CurrencyPairsHelper
end

app/views/admin/currency_pairs/edit.html.slim
h1.center Currency Rate

h3 Admin Edit Rate

= form_with model: pair, url: admin_path, class: 'admin', local: true do |f|
  = render 'shared/error', resource: pair
  .form-group.select
    = f.collection_select :currency_base, currencies, :code, :code, {prompt: 'USD'}, class: 'form-control'
    = f.collection_select :currency_quote, currencies, :code, :code, {}, class: 'form-control'
  h5 = pair.pair
  .form-group
    = f.label :price
    = f.number_field :price, class: 'form-control', step: :any
  form-group
    = f.label :date_force
    = f.datetime_local_field :date_force, class: 'form-control'
  .form-group
    = f.submit

app/views/currencies/_currency.html.slim
= link_to  find_pair_currency_pair_path(currency), method: :post, remote: true do
  li[data-code="#{currency.code}"] = currency.code

app/views/currency_pairs/_currency_pair.html.slim
= form_with url: find_pair_path, class: 'currency_pair' do |f|
  #base.currency
    = f.collection_select :currency_base, @currencies, :code, :code, {prompt: 'USD'}, class: 'currency__code'
    = f.number_field :price, value: 1, class: 'currency__price', step: :any
    span.currency__sign $
  #quote.currency
    = f.collection_select :currency_quote, @currencies, :code, :code, {}, class: 'currency__code'
    = f.number_field :price, value: @pair.price, class: 'currency__price', step: :any
    span.currency__sign ₽
    = f.submit class: 'hidden btn-form'

app/views/currency_pairs/index.html.slim
h1.center Currency Rate

= render 'currency_pair', pair: @pair, currencies: @currencies

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | DollarRate
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container
      = render 'shared/flash'
      = yield

app/views/shared/_currency_pair.html.slim
.currency-pair
  .currency
    span.currency__code = pair.base.code
    span.currency__price 1 #{pair.base.sign}
  .currency
    span.currency__code = pair.quote.code
    span.currency__price #{pair.price} #{pair.quote.sign}

app/views/shared/_error.html.slim
- if resource&.errors.present?
  b "#{resource.errors.count} error(s) detected"
  ul
    - resource.errors.full_messages.each do |msg|
      li = msg

app/views/shared/_flash.html.slim
- flash.each do |key, msg|
  = content_tag :div, msg.html_safe, class: "alert alert-#{key}", role: 'alert'